---
  .travis.yml:
    hc_secure: "O4brQNu9Hk4IUfgaNU+R8QWe0A/5ucmEBzTPX3kzrCXALHP1f4opc3MgIFzPohc/O9Y64oNcV/TZk2Bwy1mUunxCubfQfF4G1VoE0yQc/z7qOBOrYPvOU2S5srcrbwyg7zBt1H0dXKoDvgoW4fSTz4LMv3ahIlYZYmgmaeZioE4="

